### PR TITLE
Change product name to fix Discord status conflict

### PR DESCRIPTION
**Pull request by ktwrd**
## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects

note: This PR replaces my previous one, #121 

Changed property `productName` and `build.appx.displayName` in `package.json` to fix Discord Status, which then changes the Windows Executable to `Revolt Desktop.exe` instead of `Revolt.exe` to not get confused with the game Re-Volt.

Tested and working;
* [x] Windows Installer
* [x] Windows Portable (only difference is that the filename is changed, duh)
* [x] AppX Windows (Unaffected)
  * note: display name will change from `Revolt` to `Revolt Desktop`
* [x] macOS
  * unable to test myself since I do not have anything running macOS
* [x] Linux (AppImage)
  * AppImage will start with `Revolt Desktop-` instead of `Revolt-`.
  * This will not break any pipelines since they use wildcards to move to the directory for publishing.
* [x] Linux (Archive)
  * Unaffected since it uses `package.name` instead of `package.productName`

### CODE REVIEW

**Review by Nightcaat — APPROVED** [review]

**Comment by X-lem** [comment]
I personally would vote for this change. As other's have said this is a Discord issue, but there's basically a 0% chance that Discord will fix this. This is a simple change Revolt can make to bypass this Discord bug. I personally don't keep Revolt open simply because I don't want this faulty Discord status. I would assume other's do the same. Some people are going to slowly transition from Discord to Revolt and Imo this is a simple cleanup solution.

It seems others have had success changing the .exe file name, but I don't think this is possible for everyone. I'm on Windows 10 and installed Revolt through the app store. The app is installed in `C:\Program Files\WindowsApps\...` and even as administrator I have not found a way to update the exe file (permission denied).

**Comment by ktwrd** [comment]
it's been over 3mo since this PR opened and idfk why it hasn't been merged yet /shrug

**Comment by theAkito** [comment]
> it's been over 3mo since this PR opened and idfk why it hasn't been merged yet /shrug

You asked for it, so here are a couple of potential answers.

1. I know why you would have Discord & Revolt open at the same time, however you still have the choice to only have one of them open, preferably the open source solution.
3. As far as I know, the people working here are not involved with the company behind Discord. If they aren't paid by them to do shit like this, they shouldn't.
4. It's most of the time bad practice to fix other projects' issues. In this case, it's supposed to be never fixed by the other project, but there are other reasons why it's still a bad idea, which follow in this list.
5. You want to change the name of this huge program, due to a simple game nobody gives a damn about & probably nobody knows. It has 800+ reviews on Steam & costs a couple of bucks **without** any discount.
6. Changing the binary name in the way proposed basically means entirely destroying the whole logic of it.
    i. The proposed name is much longer, than the previous one.
    ii. The proposed name has a space in it. That's just mind-boggling & makes your head shake until it falls off.
    iii. The proposed name adds an entire, comparatively long, word to the binary, which does not make any sense. Yeah, no kidding, I'm running an `exe` file on the desktop. Thanks for telling me the obvious. Like, what the heck.

So, instead of trying to **** the shit out of this binary & leave it to rot in some hidden alley at the back of an Alabama building, the name should stay the same, or the newly proposed name should keep the elegance by for example shortening it to `rev.exe` or something, rather than completely butchering it & hanging it on the wall as the ugliest painting in the world.

Shit on Discord btw. Stop using it, altogether!

**Comment by ktwrd** [comment]
> You asked for it, so here are a couple of potential answers.
> ...

There is no need for this amount of toxicity. Actually, any toxicity.

So I'll answer your comment in a manner that somewhat matches you.
1. Not everyone has moved to Revolt and currently it isn't feature complete compared to Discord. It makes logical sense to have both open.
2. From my amount of experience with Revolt. They want users to have a seamless experience and having custom rich presence is one factor so they can easily tell others what platform they've moved to. Asking the user to rename an executable (on windows) means you also have to change the shortcut, which some users may not know how to.
3. Discord *does* identify "official" games by the executable/process file name.
4. See answer no.2
5. See answer no.2. Also we can't do anything about it other than changing the executable name.
6. If something you're doing to the revolt client that depends on the executable name *manually* then you're doing something wrong. I made this PR to avoid issues. Afik everything in the desktop repo actually pulls from the package.json instead of hard-coding it. 
7. Ok, and?
  i. [A PR](https://github.com/revoltchat/desktop/pull/163) was merged about 3 weeks ago which names it (on Linux) to Revolt Desktop.
  ii. Adding a space will not break other platforms such a Linux because it will use a `-` instead. Adding spaces to executable names are fine (especially on windows) since the file path to anything in your home folder usually contains a space because the account creation assumes your display name is the same as your username.

**Comment by ktwrd** [comment]
I've checked AppImage's and they are unaffected by pipelines.
  * AppImage will start with `Revolt Desktop-` instead of `Revolt-`.
  * This will not break any pipelines since they use wildcards to move to the directory for publishing.

**Comment by ktwrd** [comment]
Latest commit also just rebases from `revoltchat/desktop/orign/master`

**Comment by ktwrd** [comment]
bumping

**Comment by insertish** [comment]
Required tests:
- [ ] Works on macOS
- [ ] Does not affect "program entry" on macOS, AppX, AppImage, (AUR, Nix, or FlatPak) distribution
  i.e. the application name when searching for it, and when open, is still just "Revolt" but the executable is 'Revolt Desktop' (or the appropriate filename)

**Comment by ktwrd** [comment]
@insertish It has been tested on Windows (Installer and AppX) and Linux (AppImage and Flatpak) already with no issues when I tested it ~3mo ago and when I last updated this PR.

**Comment by insertish** [comment]
> It has been tested on Windows (Installer and AppX) and Linux (AppImage and Flatpak) already with no issues when I tested it ~3mo ago and when I last updated this PR.

Does it retain the 'Revolt' name on the actual application and in places like the start/application menu?
i.e. it doesn't show 'Revolt Desktop' when looking for or running the application itself

That was my only concern there which was a bit non-obvious from the PR description.

**Comment by ktwrd** [comment]
@insertish It does not retain the name in the shortcuts as `Revolt`, it will show `Revolt Desktop` (from what I remember)

**Comment by insertish** [comment]
> It does not retain the name in the shortcuts as `Revolt`, it will show `Revolt Desktop` (from what I remember)

Is there any way to avoid that?

**Comment by insertish** [comment]
> > It does not retain the name in the shortcuts as `Revolt`, it will show `Revolt Desktop` (from what I remember)
> 
> Is there any way to avoid that?

Bump. I do not want to change our branding just to accommodate for another platform.

**Comment by insertish** [comment]
Stale issue, closing.
I'm not compromising our brand to accommodate for other platforms, this may be fixed by Tauri in the future.

**Pull request closed without merging**
