### PR TITLE
Change executable name to fix Discord status conflict

### PR DESCRIPTION
**Pull request by ktwrd**
## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [ ] These changes do not have any notable side effects on other Revolt projects

Changed property `build.productName` in `package.json` to fix Discord Status, which then changes the Windows Executable to `Revolt Desktop.exe` instead of `Revolt.exe` to not get confused with the game Re-Volt.

Tested and working;
* [x] Windows Installer
* [ ] Windows Portable 
* [x] AppX Windows (Unaffected)
* [ ] macOS
* [ ] Linux (AppImage)
* [x] Linux (Archive)

This also changes the Display Name for the `AppX` to `Revolt Desktop`

### CODE REVIEW

**Comment by ktwrd** [comment]
Works on Linux. Using `.tar.gz` variants of Revolt and Discord (Stable)

screenshot showing rich presence working

**Comment by Rexogamer** [comment]
Assuming this doesn't affect the displayed title, I think it might be better to go with something like "Revolt Desktop"? "Revolt Chat" feels a bit odd to me, and if you were going off the .appx data I was intending to submit a PR to change that at some point

**Comment by ktwrd** [comment]
> Assuming this doesn't affect the displayed title, I think it might be better to go with something like "Revolt Desktop"? "Revolt Chat" feels a bit odd to me, and if you were going off the .appx data I was intending to submit a PR to change that at some point

The reason why I set it to `Revolt Chat` instead of `Revolt Desktop` is because that is the same display name as the AppX Package.

But yeah, `Revolt Desktop` does sound better than `Revolt Chat`

**Review by Rexogamer — APPROVED** [review]
Approving pending further testing

**Comment by insertish** [comment]
Conflicts with your other PR.

**Comment by Rexogamer** [comment]
Are you looking at the repository or in your local files?

**Pull request closed without merging**
