### PR TITLE
feat(ci): add workflow for auto-compiling

### PR DESCRIPTION
**Pull request by NinjaCheetah**
This workflow will automatically build for Windows, Linux and macOS. This both makes it easy to try out new builds and eliminates the need for access to a specific operation system when making a release (so macOS support will be easy). For macOS, this workflow makes a universal binary (I've tested and `lipo` says the executable supports x86_64 and arm64).

Current output types:
- macOS: TAR containing Revolt.app
- Linux: TAR containing Revolt-[version].AppImage
- Windows: TAR containing the unpacked windows build

This workflow could easily be adapted to also output stuff like the Windows APPX, the unpacked Linux build, and also the checksums of these builds. If there's anything you'd like added or changed, I'm willing to do so.

### CODE REVIEW

**Comment by insertish** [comment]
This looks pretty nice, does it have to be in a tar?
And for the Windows unpacked build, I would instead use a zip.

Also I would provide:
- Linux standalone binaries tar.gz
- Potentially the Windows setup too?
  Could this be setup in a way that it could also build tagged releases and upload all the assets?

**Comment by NinjaCheetah** [comment]
The TAR thing isn't needed at all, it was just a leftover from the workflow I based this on. I'll change that for the Windows build. Linux tar.gz is an easy change too. Windows setup is something I wanted to add but I wasn't sure how, but I'll look into it.

In theory you could have it run a slightly different workflow (might be able to do it in the same file) when a new tag is published that will publish the assets too. I'll also look in to that.

For now I'll add in a Linux tar.gz and switch to a .zip for Windows, should only take ~15 minutes.

**Comment by NinjaCheetah** [comment]
Alright so the Windows unpacked build is now a .zip and it publishes a tar.gz (or at least I think, the extension just says tar but the file is created as a tar.gz and it's also named 0.tar for some reason. Still works tho.) for Linux.

**Comment by NinjaCheetah** [comment]
Alright the workflow now makes:
__Linux:__
- AppImage
- tar.gz

__macOS:__
- zipfile

__Windows:__
- Setup EXE
- zipfile

**Comment by insertish** [comment]
I don't have anything to test the Mac version on, but you could send screenshots of it here and we could discuss that.

**Comment by NinjaCheetah** [comment]
Here it is running:
Screen Shot 2021-11-12 at 3 40 41 PM
And here's the example DMG I threw together:
Screen Shot 2021-11-12 at 3 41 32 PM
Only issue I've seen with the app on macOS is the small icon: 
Screen Shot 2021-11-12 at 3 43 26 PM
Looks fine when it uses the bigger one
Screen Shot 2021-11-12 at 3 43 40 PM

**Review by insertish — APPROVED** [review]
Ready to merge.
Note: I'm going to leave the macOS icon issue in favour of adding this in now.
Note 2: It may be worth creating a separate issue for it.

**Comment by NinjaCheetah** [comment]
Sounds good 👍

**Pull request merged**
