### PR TITLE
feat(ci): generate a DMG rather than a ZIP

### PR DESCRIPTION
**Pull request by NinjaCheetah**
Changed the macOS workflow to create a DMG instead of a ZIP for more user-friendliness.

Here's what it looks like:
Screen Shot 2022-01-19 at 9 08 16 PM 
Color matched the background to the Revolt red and matched the font at the bottom to the one on the website.

I can edit that background image if needed. I know the red is bright but I'm trying to use the Revolt colors and using the dark blue/black color as the background just doesn't look right. You can see it [in this comment from my original PR](https://github.com/revoltchat/desktop/pull/44#issuecomment-967520442) where I added the workflows and first tried this out.

### CODE REVIEW

**Comment by mattgeowild** [comment]
[revolt_macos.icns.zip](https://github.com/revoltchat/desktop/files/7945783/revolt_macos.icns.zip)
I would use this icon so it matches Big Sur icons' more rounded shape and smaller size.

**Comment by NinjaCheetah** [comment]
@mattgeowild Gave it a try but unfortunately changing the icon would require changes to the code (changes that I'm not really sure how to make). If Revolt's icon does get updated to a macOS-style one in the future it should just work with my script tho. 

I'm attaching a ZIP file with 16x16-1024x1024 versions of the Big Sur-style icon in case anyone could use it. Ran it through the macOS app "Bakery" so they all have nice drop shadows. (Including this because these are probably what you'd need to change the app's icon, rather than an icns)

[mac icons.zip](https://github.com/revoltchat/desktop/files/7946661/mac.icons.zip)

**Comment by NinjaCheetah** [comment]
Going to rework this slightly so it's compatible with recent changes.

**Comment by insertish** [comment]
Almost ready to merge just want @infi to take a look over and update the assets to better suit our current branding.

**Comment by insertish** [comment]
Switching to on merge:

background

**Pull request merged**
