### PR TITLE
ci: create proper DMG through package.json

### PR DESCRIPTION
**Pull request by NinjaCheetah**
The DMG created by `yarn build:mac` now matches the one created through the script. The `dmg-files/` directory has been removed and relevant build files have been moved to `build/dmg/`. The CI run publishes this DMG which should cut down on build times since it can skip the step to install `create-dmg`.

`electron-builder` was updated from v22 to v23 to support using Python 3 for the DMG creation script, allowing the app to be built on macOS 12.3+ which does not offer Python 2. This introduces a bug with universal builds that is mitigated with
```
"files": "!node_modules/**/*.{mk,a,o,h}"
```
in Package.json. No issues appeared for Linux or Windows.

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects

### CODE REVIEW

**Comment by insertish** [comment]
Currently conflicting, might have been fixed by #123 since I saw it changed these files.

**Comment by NinjaCheetah** [comment]
I see that #123 does part of the work that I did. I should be able to pretty easily rebase my changes on top of that and then it should be an easy merge. I'll also test my workflow again some to make sure the new changes to the package.json don't break there.

**Comment by NinjaCheetah** [comment]
Ok it seems that #123 got rid of universal macOS builds. I'm reverting this change as I don't see any reason why you would want separate x86/ARM builds.

**Comment by NinjaCheetah** [comment]
Making a new overview of the changes I've made (this will be updated as I work):
- Added DMG assets for macOS builds
- Switched back to universal builds for macOS (reverts a change in #123)
- Fixed Linux builds by removing the `ia32` architecture (Electron doesn't offer builds for ia32, reverts a change in #123)
- Updated Actions features to Node.js 16 (removes warning from GitHub about Node.js 12 actions being deprecated)
- Fixed Actions workflows for building (macOS is done, Linux/Windows are in progress)

**Review by insertish — APPROVED** [review]
lgtm

**Pull request merged**
